### ISSUE TITLE
Errors when building for Win10/64 and VC2022

### ISSUE THREAD

**Issue by Alienizering** [GlebchanskyGit/SolarSystem-3D#1]
Hello and thank you for your nice project. However, I'm not able to successfully build it. I get 1 success and 1 failed with the following errors...

Error	C2079	'Star::_starOcclusion' uses undefined class 'std::array<GLuint,2>'	SolarSystem	C:\SolarSystem\src\Solar_System\Star.h	60	

Error	C3646	'_nearestPlanetIndex': unknown override specifier	SolarSystem	C:\\SolarSystem\src\Application.h	39	

Error	C2589	'(': illegal token on right side of '::'	SolarSystem	C:\SolarSystem\src\Application.cpp	255	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'ssize_t': undeclared identifier	SolarSystem	C:\SolarSystem\src\Application.cpp	1093	

and so on!!!

I've downloaded, ran cmake, loaded the solution, set to release, set all the includes for GL/SDL etc. build. Am I doing it wrong?

**Comment by GTruf** [comment]
@Alienizering 
Hi, thanks for the review and sorry for the long wait! To be honest I haven't tested build of my project with Visual Studio compiler, from the very beginning everything was built with mingw and GCC. I can rebuild everything with MSVC, just let me know if it's still relevant to you.

**Comment by GTruf** [comment]
Issue is closed due to long inactivity.
